//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GFDecoder.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GFDecoder.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 执行.
        /// </summary>
        internal static string btnGoText {
            get {
                return ResourceManager.GetString("btnGoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 浏览....
        /// </summary>
        internal static string btnJsonText {
            get {
                return ResourceManager.GetString("btnJsonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 输出.
        /// </summary>
        internal static string chkSplitText {
            get {
                return ResourceManager.GetString("chkSplitText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 源Json.
        /// </summary>
        internal static string lblJsonText {
            get {
                return ResourceManager.GetString("lblJsonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 处理.
        /// </summary>
        internal static string lblProcessText {
            get {
                return ResourceManager.GetString("lblProcessText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 拆分.
        /// </summary>
        internal static string lblSplitText {
            get {
                return ResourceManager.GetString("lblSplitText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to json文件 (*.json)|*.json|所有文件 (*.*)|*.*.
        /// </summary>
        internal static string openFileDialogFilter {
            get {
                return ResourceManager.GetString("openFileDialogFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 少女前线Json处理工具.
        /// </summary>
        internal static string ToolFormText {
            get {
                return ResourceManager.GetString("ToolFormText", resourceCulture);
            }
        }
    }
}
